using System;
using System.Data;
using System.Configuration;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;

using System.Net.Mail;
using BO;
using BO.Helpers;
namespace Ticket.BO
{
    /// <summary>
    /// Summary description for NotifyObj
    /// </summary>
    public class NotifyObj
    {
        public NotifyObj()
        {
            //
            // TODO: Add constructor logic here
            //
        }
        public static void MailAdmin(int TicketNum, string origin, string status)
        {
            MailMessage mail = new MailMessage();
            mail.From = new MailAddress("admin@region5systems.local");
            mail.To.Add(ConfigSection.NotifyEmail);
            mail.Subject = "There is a new ticket from " + origin + ". Status: " + status;
            mail.Body = "Please be aware that a trouble ticket has be generated by " + origin + ". You may view it by clicking <a href=" + ConfigSection.WebUrl  + "/Trouble/ManageTickets/AdjustTicket.aspx?TicketID=" + TicketNum + ">here</a>";
            mail.IsBodyHtml = true;
            SmtpClient smtp = new SmtpClient(ConfigSection.MailServer);
            smtp.Send(mail);
        }
    }
}
